apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: forgemind-agents
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: agent
  namespaceSelector:
    matchNames:
      - forgemind
  endpoints:
    - port: http
      interval: 30s
