apiVersion: apps/v1
kind: Deployment
metadata:
  name: { include "copilot-console.fullname" . }
spec:
  replicas: { .Values.replicaCount }
  selector:
    matchLabels:
      app: { include "copilot-console.name" . }
  template:
    metadata:
      labels:
        app: { include "copilot-console.name" . }
    spec:
      containers:
        - name: { .Chart.Name }
          image: "{ .Values.image.repository }:{ .Values.image.tag }"
          imagePullPolicy: { .Values.image.pullPolicy }
          ports:
            - containerPort: 80
