apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-agent-config
  namespace: forgemind
  labels:
    app: cloudwatch-agent
data:
  config.json: |
    {
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/forgemind/*.log",
                "log_group_name": "forgemind-log-group",
                "log_stream_name": "{instance_id}"
              }
            ]
          }
        }
      }
    }
