apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgemind-efs-pvc
  namespace: forgemind
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: forgemind-efs-pv
