apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
  name: { include "reflector-agent.fullname" . }
spec:
  type: { .Values.service.type }
  ports:
    - port: { .Values.service.port }
  selector:
    app: { include "reflector-agent.name" . }
