apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-rolebinding
  namespace: forgemind
subjects:
  - kind: ServiceAccount
    name: default
    namespace: forgemind
roleRef:
  kind: Role
  name: agent-role
  apiGroup: rbac.authorization.k8s.io
