# .github/workflows/apply-if-approved.yml
name: Apply If Approved

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=infra init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve -var-file=terraform.tfvars

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Generate kubeconfig
        run: |
          CLUSTER_NAME=$(terraform -chdir=infra output -raw eks_cluster_name)
          CLUSTER_ENDPOINT=$(terraform -chdir=infra output -raw eks_cluster_endpoint)
          CLUSTER_CA=$(terraform -chdir=infra output -raw eks_cluster_ca)
          scripts/generate-kubeconfig.sh "$CLUSTER_NAME" "$CLUSTER_ENDPOINT" "$CLUSTER_CA" us-east-1 ./kubeconfig
      - name: Upload kubeconfig
        uses: actions/upload-artifact@v3
        with:
          name: kubeconfig
          path: kubeconfig
