name: Helm Deploy

on:
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:

jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Deploy with Helm
        run: helm upgrade --install my-release ./charts
