name: Reflect and Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  reflect:
    runs-on: ubuntu-latest
    steps:
      - name: Sync memory to S3
        run: echo "Syncing memory state..."
