# .github/workflows/reflect-and-sync.yml
name: Reflect and Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  reflect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ensure memory path exists
        run: mkdir -p .aiops/memory/logs

      - name: Run Lock Tracker
        run: python scripts/lock_tracker.py

      - name: Sync memory to S3
        run: aws s3 sync .aiops/memory/ s3://forgescaler-memory/logs/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Generate Markdown Reflection Log
        run: python scripts/render_reflection_md.py
