name: Sync Memory to S3

on:
  workflow_run:
    workflows: ['Reflect and Sync']
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Upload memory logs to S3
        run: echo "Uploading logs to S3..."
